language: node_js
node_js:
- '6.2'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 6.2.2
branches:
  only:
  - dev
services:
- mongodb
cache:
  directories:
  - node_modules
  - client/bower_components
before_script:
- npm install -g bower gulp-cli gulp
- npm install --only=dev
- npm install gulp
- npm install grunt
- npm install babel babel-preset-es2015 babel-plugin-transform-class-properties
- bower install
after_success:
- bash ./travis/after_success.sh
